name: Python Build

on:
  push:
    branches: [ main, actions ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  DEBUG_OUTPUT: false

jobs:
  linux-build:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04, macos-11, macos-10.15]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Install mivp_agent
      run: cd src/python_module && pip3 install .
    - name: Install mivp_agent testing deps
      run: cd src/python_module && pip3 install .[test]
    - name: Run python tests
      run: cd src/python_module/test && ./test_all.py
