name: Python Build

on:
  push:
    branches: [ main ]
    branches: [ actions ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release
  DEBUG_OUTPUT: false

jobs:
  linux-build:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Install pip dependencies? # Pip will faill on ubutun 18 on step bellow without this
      run: sudo apt-get update && sudo apt-get install -y python3-setuptools
    - name: Install mivp_agent dependencies
      run: pip3 install numpy matplotlib
    - name: Install mivp_agent testing dependencies
      run: pip3 install timeout-decorator
    - name: Run python tests
      run: cd src/python_module/test && ./test_all.py
